### ISSUE TITLE
You can't add another file extension in filter using GUI

### ISSUE THREAD

**Issue by aibread** [jordfocus/CleRexTool#1]
You use next statement to find all fies
var files = Directory.GetFiles(projectFolder, filter, SearchOption.AllDirectories);
but this statement doesn't work if you need several file extentions.
for example to search in *.xaml files too we need something like this
var files = Directory.GetFiles(projectFolder, "*.*", SearchOption.AllDirectories).Where(str => str.EndsWith(".cs") || str.EndsWith(".xaml"));

**Comment by j0rdan-dev** [comment]
You can search for multiple file extensions and you need to specify those in the filter. That is set in this text field 
![image](https://user-images.githubusercontent.com/2544708/39048578-48c400a8-449e-11e8-8284-2945b4c2565b.png)
